### ISSUE TITLE
Http2 Request failing with Cache-Control: public, must-revalidate, max-age=86056

### ISSUE THREAD

**Issue by anupam-nagarro** [Blazemeter/jmeter-http-plugin#15]
The http2 request to my server is failing as I am receiving the response in the headers but not in the body. Also in JMeter it is throwing an error with respect to the same request.
![1](https://user-images.githubusercontent.com/52594191/126751724-80a6c6f7-3318-4b87-82dc-a71203d80bae.jpg)

````java
java.util.zip.ZipException: Not in GZIP format
        at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at com.blazemeter.jmeter.http2.sampler.HTTP2StreamHandler.gzipDecompressor(HTTP2StreamHandler.java:443)
        at com.blazemeter.jmeter.http2.sampler.HTTP2StreamHandler.onData(HTTP2StreamHandler.java:203)
        at org.eclipse.jetty.http2.HTTP2Stream.notifyData(HTTP2Stream.java:636)
        at org.eclipse.jetty.http2.HTTP2Stream.onData(HTTP2Stream.java:387)
        at org.eclipse.jetty.http2.HTTP2Stream.process(HTTP2Stream.java:306)
        at org.eclipse.jetty.http2.HTTP2Session.onData(HTTP2Session.java:259)
        at org.eclipse.jetty.http2.HTTP2Connection$ParserListener.onData(HTTP2Connection.java:390)
        at org.eclipse.jetty.http2.parser.BodyParser.notifyData(BodyParser.java:108)
        at org.eclipse.jetty.http2.parser.DataBodyParser.onData(DataBodyParser.java:150)
        at org.eclipse.jetty.http2.parser.DataBodyParser.emptyBody(DataBodyParser.java:60)
        at org.eclipse.jetty.http2.parser.Parser.parseBody(Parser.java:194)
        at org.eclipse.jetty.http2.parser.Parser.parse(Parser.java:127)
        at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:261)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:360)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:184)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
        at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:183)
        at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:138)
        at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:361)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:540)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:395)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
        at java.lang.Thread.run(Thread.java:748)

**Comment by RicardoPoleo** [comment]
Hello again @anupam-nagarro,

Just like your other report(#14), I'll add this issue to our backlog and let you know when it is being dealt with. 

As always, thanks for taking the time and stay tuned,

Cheers!

**Comment by 3dgiordano** [comment]
Hi @anupam-nagarro 

Could you confirm if you can still reproduce the error in version 3.1.0?

**Comment by 3dgiordano** [comment]
Closed due to lack of response.
